CREATE TABLE `SPRING_SESSION` (
`SESSION_ID` char(36) NOT NULL DEFAULT '', 
`CREATION_TIME` bigint(20) NOT NULL,
`LAST_ACCESS_TIME` bigint(20) NOT NULL, 
`MAX_INACTIVE_INTERVAL` int(11) NOT NULL,
 `PRINCIPAL_NAME` varchar(100) DEFAULT NULL,
PRIMARY KEY (`SESSION_ID`) USING BTREE,
KEY `SPRING_SESSION_IX1` (`LAST_ACCESS_TIME`) USING BTREE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

 CREATE TABLE `SPRING_SESSION_ATTRIBUTES` (
 `SESSION_ID` char(36) NOT NULL DEFAULT '',
 `ATTRIBUTE_NAME` varchar(100) NOT NULL DEFAULT '',
 `ATTRIBUTE_BYTES` blob,
 PRIMARY KEY (`SESSION_ID`,`ATTRIBUTE_NAME`),
 KEY `SPRING_SESSION_ATTRIBUTES_IX1` (`SESSION_ID`) USING BTREE,
 CONSTRAINT `SPRING_SESSION_ATTRIBUTES_ibfk_1` FOREIGN KEY
(`SESSION_ID`) REFERENCES `SPRING_SESSION` (`SESSION_ID`) ON DELETE
CASCADE
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
